"""
Dashboard application for the Cognitive Data Processing Pipeline.

This module provides a simple dashboard for viewing processed
product and startup intelligence data.
"""

from pathlib import Path
import json

import streamlit as st
import pandas as pd


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "data" / "output"
PROCESSED_DIR = BASE_DIR / "data" / "processed"


# ---------------------------------------------------------
# Page Configuration
# ---------------------------------------------------------

st.set_page_config(
    page_title="Cognitive Data Processing Pipeline",
    page_icon="📊",
    layout="wide",
)


# ---------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------

def load_json_file(file_path: Path):
    """Load JSON data from a file if it exists."""
    if not file_path.exists():
        return []

    try:
        with open(file_path, "r", encoding="utf-8") as file:
            return json.load(file)
    except (json.JSONDecodeError, OSError):
        return []


def find_json_files(directory: Path):
    """Return JSON files available in a directory."""
    if not directory.exists():
        return []

    return list(directory.glob("*.json"))


def load_data():
    """Load available product and startup data."""
    files = find_json_files(OUTPUT_DIR)

    products = []
    startups = []

    for file_path in files:
        data = load_json_file(file_path)

        if "product" in file_path.name.lower():
            products.extend(data if isinstance(data, list) else [data])

        elif "startup" in file_path.name.lower():
            startups.extend(data if isinstance(data, list) else [data])

    return products, startups


# ---------------------------------------------------------
# Header
# ---------------------------------------------------------

st.title("🧠 Cognitive Data Processing Pipeline")

st.markdown(
    """
    **AI-powered intelligence dashboard for Products and Startups**

    This dashboard provides a visual interface for inspecting the
    data generated by the Cognitive Data Processing Pipeline.
    """
)

st.divider()


# ---------------------------------------------------------
# Load Data
# ---------------------------------------------------------

products, startups = load_data()


# ---------------------------------------------------------
# Metrics
# ---------------------------------------------------------

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        label="Products",
        value=len(products),
    )

with col2:
    st.metric(
        label="Startups",
        value=len(startups),
    )

with col3:
    st.metric(
        label="Total Records",
        value=len(products) + len(startups),
    )


st.divider()


# ---------------------------------------------------------
# Navigation
# ---------------------------------------------------------

section = st.selectbox(
    "Select Data View",
    [
        "Overview",
        "Products",
        "Startups",
    ],
)


# ---------------------------------------------------------
# Overview
# ---------------------------------------------------------

if section == "Overview":

    st.subheader("Pipeline Overview")

    st.markdown(
        """
        The pipeline processes intelligence data through the following
        stages:

        **Collectors → Cleaning → Processing → Feature Extraction
        → Storage → Dashboard/API**
        """
    )

    st.subheader("Available Data")

    overview_data = {
        "Data Type": [
            "Products",
            "Startups",
        ],
        "Records": [
            len(products),
            len(startups),
        ],
    }

    st.dataframe(
        pd.DataFrame(overview_data),
        use_container_width=True,
        hide_index=True,
    )


# ---------------------------------------------------------
# Products
# ---------------------------------------------------------

elif section == "Products":

    st.subheader("📦 Product Intelligence")

    if products:
        product_df = pd.DataFrame(products)

        st.write(f"Total product records: **{len(product_df)}**")

        st.dataframe(
            product_df,
            use_container_width=True,
            hide_index=True,
        )

    else:
        st.info(
            "No product output data found. "
            "Run the pipeline first to generate product data."
        )


# ---------------------------------------------------------
# Startups
# ---------------------------------------------------------

elif section == "Startups":

    st.subheader("🚀 Startup Intelligence")

    if startups:
        startup_df = pd.DataFrame(startups)

        st.write(f"Total startup records: **{len(startup_df)}**")

        st.dataframe(
            startup_df,
            use_container_width=True,
            hide_index=True,
        )

    else:
        st.info(
            "No startup output data found. "
            "Run the pipeline first to generate startup data."
        )


# ---------------------------------------------------------
# Footer
# ---------------------------------------------------------

st.divider()

st.caption(
    "Cognitive Data Processing Pipeline • "
    "Products & Startup Intelligence"
)